package com.kalyani.car_rental_backend.address.controller;
import com.kalyani.car_rental_backend.address.dto.*;import com.kalyani.car_rental_backend.address.entity.SavedAddress;import com.kalyani.car_rental_backend.address.repository.SavedAddressRepository;
import com.kalyani.car_rental_backend.exception.ResourceNotFoundException;import com.kalyani.car_rental_backend.response.ApiResponse;import com.kalyani.car_rental_backend.user.repository.UserRepository;
import jakarta.validation.Valid;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/addresses")
public class SavedAddressController{
 private final SavedAddressRepository repo;private final UserRepository users;public SavedAddressController(SavedAddressRepository r,UserRepository u){repo=r;users=u;}
 @GetMapping public ResponseEntity<ApiResponse<List<SavedAddressResponse>>> list(Authentication a){return ResponseEntity.ok(ApiResponse.success(repo.findByUserEmailIgnoreCaseOrderByPrimaryAddressDescCreatedAtDesc(a.getName()).stream().map(this::out).toList(),"Saved addresses loaded"));}
 @PostMapping @Transactional public ResponseEntity<ApiResponse<SavedAddressResponse>> create(@Valid @RequestBody SavedAddressRequest r,Authentication a){var u=users.findByEmailIgnoreCase(a.getName()).orElseThrow(()->new ResourceNotFoundException("User not found"));if(r.primaryAddress)clearPrimary(a.getName());var e=new SavedAddress();e.setUser(u);apply(e,r);return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(out(repo.save(e)),"Address saved"));}
 @PutMapping("/{id}") @Transactional public ResponseEntity<ApiResponse<SavedAddressResponse>> update(@PathVariable Long id,@Valid @RequestBody SavedAddressRequest r,Authentication a){var e=owned(id,a.getName());if(r.primaryAddress)clearPrimary(a.getName());apply(e,r);return ResponseEntity.ok(ApiResponse.success(out(repo.save(e)),"Address updated"));}
 @DeleteMapping("/{id}") public ResponseEntity<ApiResponse<Void>> delete(@PathVariable Long id,Authentication a){repo.delete(owned(id,a.getName()));return ResponseEntity.ok(ApiResponse.success(null,"Address deleted"));}
 private SavedAddress owned(Long id,String email){var e=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Address not found"));if(!e.getUser().getEmail().equalsIgnoreCase(email))throw new IllegalArgumentException("You cannot access this address");return e;}
 private void clearPrimary(String email){repo.findByUserEmailIgnoreCaseOrderByPrimaryAddressDescCreatedAtDesc(email).forEach(x->{if(x.isPrimaryAddress()){x.setPrimaryAddress(false);repo.save(x);}});}private void apply(SavedAddress e,SavedAddressRequest r){e.setLabel(r.label.trim());e.setAddressLine(r.addressLine.trim());e.setCity(r.city);e.setState(r.state);e.setPostalCode(r.postalCode);e.setLatitude(r.latitude);e.setLongitude(r.longitude);e.setPrimaryAddress(r.primaryAddress);}private SavedAddressResponse out(SavedAddress e){return new SavedAddressResponse(e.getId(),e.getLabel(),e.getAddressLine(),e.getCity(),e.getState(),e.getPostalCode(),e.getLatitude(),e.getLongitude(),e.isPrimaryAddress(),e.getCreatedAt());}
}
